language: node_js
os: osx
node_js:
- "12"
install:
- npm install && lerna exec -- npm i

#before_script:
#- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.4.5-darwin-amd64 > ./cc-test-reporter
#- chmod +x ./cc-test-reporter
#- ./cc-test-reporter before-build
#- export CC_TEST_REPORTER_ID=a042520e622d465494e99073b0fa5fffe183440e3f6739880b9e687fd418aef8

script:
- lerna exec -- npm run test

#after_script:
#- npm install mocha-lcov-reporter@1.3.0
#- npm install istanbul@1.1.0-alpha.1
#- ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- test/**/*.test.js -R mocha-lcov-reporter --require @babel/register
#- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
  - "./node_modules"